nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://127.0.0.1:8000', 'http://localhost:8000', 'https://127.0.0.1:8000', 'https://localhost:8000', 'http://127.0.0.1', 'http://localhost']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        expose_headers: ['Content-Type']
        max_age: 3600
    paths:
        '^/': null
