nelmio_cors:
    defaults:
        # origin_regex: true
        # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        # allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        # allow_headers: ['Content-Type', 'Authorization']
        # expose_headers: ['Link']
        # max_age: 3600
        allow_credentials: true
        allow_origin: ['http://127.0.0.1:8000', 'http://localhost:8000']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        expose_headers: ['Content-Type']
        max_age: 3600
    paths:
        '^/': null
